baseURL       = "https://mahallgroup.ru/"
languageCode  = "ru-ru"
title         = "Mahall Group Russia"
theme         = ["roxo-hugo-modified", "matomo"]
summarylength = 25
enableRobotsTXT = true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Главная"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "О нас"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Проекты"
    url     = "portfolio"
    weight  = 3
  # [[menu.nav]]
  #   name    = "Блог"
  #   url     = "blog"
  #   weight  = 4
  [[menu.nav]]
    name    = "Связаться с нами"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "04 MAY 1993"
  # Meta data
  description = "Mahall Group Russia | Агенство недвижимости полного цикла"
  author = "Mahall Group Russia"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  # fabform  = "https://fabform.io/f/USAg2Jl"

[params.matomo]
  url = "https://matomo.analytics-abc.xyz"
  id = 3

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Имя"
    # placeholder_last_name         = "Фамилия"
    # placeholder_email             = "Почта"
    placeholder_tel               = "Телефон"
    placeholder_about_the_project = "Сообщение (необязательно)"
    send_message                  = "Отправить"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Mahall Group Russia"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Mahall Group Russia"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Связаться с нами"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/mahall-main.jpg"
    heading               = "Mahall Group — агентство недвижимости полного цикла"
    tagline               = "Мы поможем выбрать и приобрести недвижимость в Турции под ваши цели"
    primary_button        = "Посмотреть проекты"
    primary_button_url    = "portfolio"
    secondary_button      = "Связаться с нами"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Наши Проекты"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Хотите узнать, какие проекты подойдут именно вам?"
    primary_button      = "Отправить заявку"
    primary_button_url  = "contact"
    secondary_button    = "Посмотреть проекты"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Контакты"
      address = "Körfez Mah. Yunuslar Sok.<br>No: 19/B Başiskele/KOCAELİ"
      phone   = "00905334561832"
      email   = "info@mahallgroup.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Карта сайта"
        [[params.footer.sitemap.link]]
          name = "О нас"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Наши проекты"
          url  = "portfolio"
        # [[params.footer.sitemap.link]]
        #   name = "Блог"
        #   url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Связаться с нами"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Мы в соцсетях"
        [[params.footer.social.link]]
          name = "VK"
          url  = "https://vk.com/public218552225"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Наша география"
        description = "Работаем во всех регионах и крупных городах Турции от туристической Антальи до делового Коджаэли"
