baseURL       = "https://mellifluous-haupia-885bb4.netlify.app/"
languageCode  = "ru-ru"
title         = "Mahall Group Russia"
theme         = "roxo-hugo-modified"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/mahall.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "Georgy Toporkov"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Имя"
    placeholder_last_name         = "Фамилия"
    placeholder_email             = "Почта"
    placeholder_tel               = "Телефон"
    placeholder_about_the_project = "Сообщение (необязательно)"
    send_message                  = "Отправить"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Связаться с нами"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/pexels-expect-best-darkened.jpg"
    heading               = "Мы поможем выбрать и приобрести недвижимость в Турции под ваши цели"
    tagline               = "Mahall Group — агентство недвижимости полного цикла"
    primary_button        = "Посмотреть проекты"
    primary_button_url    = "portfolio"
    secondary_button      = "Связаться с нами"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Наши Проекты"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Найдём недвижимосить под ваши цели?"
    primary_button      = "Отправить запрос"
    primary_button_url  = "contact"
    secondary_button    = "Посмотреть проекты"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Контакты"
      address = "Körfez Mah. Yunuslar Sok.<br>No: 19/B Başiskele/KOCAELİ"
      phone   = "00905334561832"
      email   = "info@mahallgroup.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "О нас"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Наши проекты"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Блог"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Связаться с нами"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Мы в соцсетях"
        [[params.footer.social.link]]
          name = "VK"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Мы помогаем:"
        description = "Выбрать и приобрести недвижимость<br>оценить инвестиции<br>что-то ещё"
